### ISSUE TITLE
Failed to run a full export on a clean Magento installation

### ISSUE THREAD

**Issue by aspacca** [akeneo/MagentoConnectorBundle#218]
Hello,

I've a fresh installation of Akeneo 1.1.0, Magento Connector Bundle RC5 and Magento 1.7.2. The installerd_data in Akeneo is PimMagentoConnectorBundle:demo_magento.

When I try to make a full export the following errors occur:
ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"marketing"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"colors"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : [null,"sizes"]

Trying another export gives quite the same errores (this time with 10 instead of null):
ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","marketing"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","general"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","colors"]

ATTRIBUTE WRITER  Error on Magento soap call : "SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`magento`.`eav_attribute_group`, CONSTRAINT `FK_EAV_ATTR_GROUP_ATTR_SET_ID_EAV_ATTR_SET_ATTR_SET_ID` FOREIGN KEY (`attribute_set_id`) REFERENCES `eav_attribute_set` (`attribute_set_id`) ON DEL)". Called resource : "product_attribute_set.groupAdd" with parameters : ["10","sizes"]

**Comment by fitn** [comment]
This bug has been solved since some months. Sorry for late answer.
