### ISSUE TITLE
Export Tier Prices

### ISSUE THREAD

**Issue by marcus-hoppen** [akeneo/MagentoConnectorBundle#229]
Hello,

i've created an attribute to maintain the tier prices in akeneo. 
The following content is in the text box "admin|ALL GROUPS|5000|0.70||admin|ALL GROUPS|10000|0.65||admin|ALL GROUPS|15000|0.60" . 
After that i mapped the attribute in the Magento Connector Profile: tier_price = tier_price.

The export profile was carried out, but unfortunately the tier prices has been exported to Magento.

Is there any possibility to export tier prices ?

**Comment by fitn** [comment]
Hello,

This feature won't be supported cause Akeneo managed only data informations not pricing.

Regards,
