### ISSUE TITLE
no Magento export profile after fresh Akeneo and MagentoConnectorBundle install

### ISSUE THREAD

**Issue by ZuzanaPetrakovaPelikan** [akeneo/MagentoConnectorBundle#233]
Hi,
our hosting provider installed for us akeneo and MagentoConnectorBundle with no errors.
Unfortunately, we cannot see any Magento menu in akeneo neither possibility of Magento export profile while creating new export profile. Could you please give us hint what may be the problem in this case?

Thank you very much.

Sincerely,

Zuzana

**Comment by kavithakpits** [comment]
I am also getting this same issue. but magento connector is installed and showing in vendors folder
