### ISSUE TITLE
Base Image not set for configurable products

### ISSUE THREAD

**Issue by tom00** [akeneo/MagentoConnectorBundle#234]
![screen shot 2014-07-29 at 5 34 04 pm](https://cloud.githubusercontent.com/assets/6136403/3737364/5a0ef708-1736-11e4-9bac-cf37ca69524b.png)

While this setting is working correctly for simple product export, when creating/updating a configurable product, only an image is copied but the base image setting is not applied.

![screen shot 2014-07-29 at 5 41 13 pm](https://cloud.githubusercontent.com/assets/6136403/3737444/0900482a-1737-11e4-8d9b-a2238f1198c0.png)

**Comment by fitn** [comment]
Sorry for late,

We fixed that issue some months ago.

Regards,
