### ISSUE TITLE
Incorrect configurable attributes chosen in case not all used to build configurable product

### ISSUE THREAD

**Issue by tom00** [akeneo/MagentoConnectorBundle#236]
Magento Connector does not send the information which attribute is the axis attribute.
This may provide to a situation that a configurable product is incorrectly formed in case when in magento there are more attributes with "Use To Create Configurable Product" option set but not all of them are actually used to build the configurable products.

BubbleAPI extension provides an ability to define which configurable attributes to use.

This is a fix I prepared for my case. Maybe you find it useful.
ConfigurableNormalizer.php:180 in method getDefaultConfigurable()

```php
        $configurableAttributes = [];
        $configurableAttributes['configurable_attributes'] = [];

        foreach ($group->getAttributes() as $attribute) {
        	$configurableAttributes['configurable_attributes'][] = $attribute->getCode();
        }

        $defaultConfigurableValues = array_merge(
            $defaultProductValues,
        	$configurableAttributes,
            $priceMapping,
            [self::ASSOCIATED_SKUS => $associatedSkus]
        );
```

**Comment by damien-carcel** [comment]
Hello Tom00,

This bug is now fixed in the last version of the Magento connector bundle (v1.1.11).
Thanks again for your feedback.
