### ISSUE TITLE
Compatibility with PIM 1.3

### ISSUE THREAD

**Issue by jarocks** [akeneo/MagentoConnectorBundle#249]

**Comment by tempoecommerce** [comment]
I can add a comment while I am receiving an error as well.

With akeneo 1.3 the requirements are not set correct. It does not recognize akeneo 1.3 and says you need at least akeneo 1.2

**Comment by albertomrossi** [comment]
Hi all i'm interested too in installing this connector with PIM 1.3

can you please advise?
thanks and best,
alberto

**Comment by fitn** [comment]
Hi @jarocks, @tempoecommerce, @albertomrossi 

We are currently working on this compatibility and it's already available on the master branch. We'll release the 1.2 really soon.

Regards,
