### ISSUE TITLE
Not working with Magento EE 1.10

### ISSUE THREAD

**Issue by manh-nguyen** [akeneo/MagentoConnectorBundle#338]
It seems this bundle is not working with Magento EE 1.10.

My magento is Magento EE 1.10. Can you please guide me how to make your bundle work with Magento EE 1.10? I will spend time to code more functionality to help this supporting it.
Just guide me how to do it and where should i look into?

It's really important for me. So please help me.

Regards,
Manh - Balance Internet

**Comment by manh-nguyen** [comment]
Hi @fitn ,
Thank you very much for replying me.

We are using
pim-community-standard v1.2.8
MagentoConnectorBundle v1.1.8 (2014-12-01)
Magento EE v1.10.0.1

It shows error when i'm trying to save Export profile:
"Error on Magento soap call : "Invalid api path.". Called resource : "core_magento.info" with parameters : null"

I've tested this configuration with Magento EE 1.13 and it's working.

And then i looked into vendor\akeneo\magento-connector-bundle\Pim\Bundle\MagentoConnectorBundle\Guesser\AbstractGuesser.php
and saw 

    const MAGENTO_VERSION_1_14 = '1.14';
    const MAGENTO_VERSION_1_13 = '1.13';
    const MAGENTO_VERSION_1_9  = '1.9';
    const MAGENTO_VERSION_1_8  = '1.8';
    const MAGENTO_VERSION_1_7  = '1.7';
    const MAGENTO_VERSION_1_6  = '1.6';

    const MAGENTO_VERSION_NOT_SUPPORTED_MESSAGE = 'Your Magento version is not supported yet.';

If you guys already made it compatible with Magento EE 1.10 , please tell me the way to configure the Magento Connector bundle.

Regards,
Manh

**Comment by fitn** [comment]
Hi @manh-nguyen 

Ok I get it. So Magento EE v1.10 is based on Magento CE v1.5 which has not any API (in anycase we don't support it). So indeed, you should update your Magento to use our connector.

Regards,

**Comment by manh-nguyen** [comment]
hey @fitn ,

Can you look into this link: https://docs.google.com/document/d/1VoFq5ByWUu9i1lSFj2V0FlsMb0DaSXnU5eSJylIm2ls/edit?usp=sharing 
(Magento EE API compare: 1.10 vs 1.13)

EE v1.10 supports 60 API methods and probably it doesn't have core_magento.info api.
Can you tell me which Magento APIs you guys are using in this bundle? If it's lucky, your used APIs are existing in EE v1.10 except core_magento.info api .

It's really important for me, bro and our client doesn't has any plan to upgrade Magento to newer version at this moment.

Please help me to check it or tell me where should i go to find it !

Thank you very much @fitn !!!
Regards,
