### ISSUE TITLE
Best Practice for Updating

### ISSUE THREAD

**Issue by tegansnyder** [akeneo/MagentoConnectorBundle#349]
What is the best method to continually update and track this repo along with the PIM Community Standard repo?

Do I just do something like this?
```bash
cd /my/pim/installation/dir
composer update
php app/console doctrine:schema:update --force
php app/console pim:installer:assets
```

Thanks!

**Comment by fitn** [comment]
Hi @tegansnyder 

Yep it's a good practice but it depends on what you added in your composer.json in fact. It should be 1.1.*.
In production mode, you've to restart Apache to clean your cache.

Regards,
