### ISSUE TITLE
Magento 1.4 compatibility ?

### ISSUE THREAD

**Issue by qosdevelopment** [akeneo/MagentoConnectorBundle#359]
Hello,
 The magento connector give me this issue with magento 1.4 
Error on Magento soap call to "http://195.XX.XX.XX:80XX/index.php/api/soap/?wsdl" : "Invalid api path.". Called resource : "core_magento.info" with parameters : null

With magento 1.9 I have no problem. the connector is not compatible with 1.4 ?

Thanks for answer
YL

**Comment by fitn** [comment]
Hi @qosdevelopment 

Unfortunately, we are compatible only from CE 1.6 to CE 1.9 and from EE 1.13 to EE 1.14. We use Magento API so we can't make it work with Magento 1.4.

I'll add compatibility informations in README file.

Regards,
