### ISSUE TITLE
Magento 1.9, delete/disable SKU

### ISSUE THREAD

**Issue by qosdevelopment** [akeneo/MagentoConnectorBundle#360]
Hello,

 I think there is a bug when deleting or disabling product. You call the webservice with SKU, maybe you have to do it with the product id ?!
 Both website_id and sku exists on magento side.

Magento 1.9.1.0

Thanks
YL

![pim_delete_item_pb](https://cloud.githubusercontent.com/assets/10493094/5699745/76dac7b4-9a2f-11e4-931b-228ce00c84d6.PNG)

**Comment by fitn** [comment]
Hi @qosdevelopment ,

On which version of the connector are you based? We'll try to reproduce this issue.

Regards

**Comment by qosdevelopment** [comment]
J'ai suivi la procédure d'installation cette nuit avec la méthode composer, le release note me dit : 1.1.12

Effectivement la doc parle du product id ou du sku avec un argument supplémentaire, en magento 1.4 je n'ai jamais réussi à faire fonctionner via SKU. Je découvre la 1.9 depuis aujourdhui.

YL

**Comment by damien-carcel** [comment]
Hi @qosdevelopment .

On my side, I cannot reproduce this behavior. Like, you, I use the Magento connector bundle v1.1.12 and Magento 1.9.1 . Did you install the connector with the pim-community-standard ?

Could you describe exactly what you did to obtain this behavior ? What data did you export, what modifications you did on these data before export ?

Regards

**Comment by qosdevelopment** [comment]
Hi,

 Yes it's the pim/community/standard. My actual platform is just a test and not critical at all, would you like an acces to see by yourself ?

YL

**Comment by damien-carcel** [comment]
Indeed, it could be very helpful.
You can email me details at damien.carcel@akeneo.com, if you don't want to publicly post the access (you never know what bot can collect it ;) ).

**Comment by damien-carcel** [comment]
It appears that your problem come from using icecat_demo fixtures to test the Magento connector. These fixtures are not prepared to work with Magento. It is better to use the Magento demo fixtures, as explained in the “Demo fixtures” section at the end of the Readme.
Then you can use your own data to expend and realize bigger export tests.

**Comment by qosdevelopment** [comment]
I will try a clean install and my own data on monday. we keep in touch.

Thanks
YL
