### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by cloudswork-ruud** [akeneo/MagentoConnectorBundle#419]
I get the following error when installing the bundle:
akeneo/magento-connector-bundle v1.1.9 requires akeneo/pim-community-dev 1.2.*@stable -> no matching package found.

how can I fix this?

**Comment by damien-carcel** [comment]
Hi.

v1.1.9 is an old version. I recommand you to install the last 1.1.*@stable version.

Also, did you by any chance install the connector with Akeneo 1.3? The actual version of the connector is actually not compatible with Akeneo 1.3. You must for the moment use Akeneo 1.2, by installing the last pim-community-standard 1.2 : https://github.com/akeneo/pim-community-standard/releases

**Comment by cloudswork-ruud** [comment]
Yes I am using Akeneo 1.3

Will it take a long time before 1.2 is going to be released?

**Comment by cloudswork-ruud** [comment]
Isn't there a way to make it work with Akeneo 1.3, as I want to go live with my new website.

**Comment by fitn** [comment]
Hi @cloudswork-ruud 

We're currently working on this compatibility and there is no stable version right now. A new version will be release soon ;)

Regards,

**Comment by fitn** [comment]
Ok I close this enhancement. Magento connector 1.2 is compatible with PIM 1.2 and 1.3 ;)

Regards,
