### ISSUE TITLE
magento and pim installation

### ISSUE THREAD

**Issue by vitasoa** [akeneo/MagentoConnectorBundle#421]
Hi all,

I'vfe followed this tuto installation:
https://github.com/akeneo/MagentoConnectorBundle.

1 - I've installed PIM standrat version 1.2.27 with this error:
Warning: ResourceBundle::get(): Cannot load element ‘Countries’ without fallback from to (null) in D:\wamp\www\pim\pim-project\vendor\symfony\symfony\src\Symfony\Component\Intl\ResourceBundle\Util\ArrayAccessibleResourceBundle.php on line 35.
 but it's ok!

When I try to install magento bundles with:
$ php composer.phar require akeneo/connector-mapping-bundle:v1.0.0-BETA3@dev
$ php composer.phar require akeneo/delta-export-bundle:v1.0.0-BETA3@dev
$ php composer.phar require akeneo/magento-connector-bundle:1.1.*@stable

Enable bundles in the app/AppKernel.php file, in the registerBundles function just before the return $bundles line:

$bundles[] = new Pim\Bundle\DeltaExportBundle\PimDeltaExportBundle();
$bundles[] = new Pim\Bundle\ConnectorMappingBundle\PimConnectorMappingBundle();
$bundles[] = new Pim\Bundle\MagentoConnectorBundle\PimMagentoConnectorBundle();

I can't use this command:
php app/console doctrine:schema:update --force

2 - I've tried with PIM dev master 1.4.x
When I run this command:
$ php composer.phar require akeneo/magento-connector-bundle:dev-master

I've this errors:
  Problem 1
    - akeneo/magento-connector-bundle v1.1.9 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.8 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.7 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.6 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.5 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.4 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.3 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.21 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.20 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.2 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.19 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.18 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.17 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.16 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.15 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.14 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.13 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.12 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.11 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.10 requires akeneo/pim-community-dev
1.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.1 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - akeneo/magento-connector-bundle v1.1.0 requires akeneo/pim-community-dev 1
.2.*@stable -> no matching package found.
    - Installation request for akeneo/magento-connector-bundle ~1.1 -> satisfiab
le by akeneo/magento-connector-bundle[v1.1.0, v1.1.1, v1.1.10, v1.1.11, v1.1.12,
 v1.1.13, v1.1.14, v1.1.15, v1.1.16, v1.1.17, v1.1.18, v1.1.19, v1.1.2, v1.1.20,
 v1.1.21, v1.1.3, v1.1.4, v1.1.5, v1.1.6, v1.1.7, v1.1.8, v1.1.9].

So Ho can I manage it please!

Thx

**Comment by vitasoa** [comment]
Hello,

Please send with the composer.json!!

Thx,

**Comment by fitn** [comment]
Hi @vitasoa 

dev-master is development branch so you should NOT use it for production environment. It's only for contribution ;)
We're currently preparing Magento Connector (MC) 1.2 which will be compatible with Akeneo PIM CE 1.2 and 1.3.
Akeneo PIM CE dev-master won't be compatible with MC for now.

Please reinstall the PIM without any warning and following this guide: http://docs.akeneo.com/1.2/index.html. Then add the dependency on MC 1.1.*. 

Let me know if you encounter others problems.

Regards,
