### ISSUE TITLE
Installation error w/MongoDB

### ISSUE THREAD

**Issue by vbnet3d** [akeneo/MagentoConnectorBundle#464]
We are attempting to install the connector in a MongoDB environment, PIM version 1.3.5. On attempting to install the Magento Connector, we get the following error:

PHP Catchable fatal error:  Argument 5 passed to Pim\Bundle\MagentoConnectorBundle\Reader\MongoDBODM\DeltaProductReader::__construct() must be an instance of Doctrine\ODM\MongoDB\DocumentManager, instance of Oro\Bundle\EntityBundle\ORM\OroEntityManager given, called in /var/www/pim-project/app/cache/pro_/ap_ProdProjectContainer.php on line 7701 and defined in /var/www/pim-project/vendor/akeneo/magento-connector-bundle/Pim/Bundle/MagentoConnectorBundle/Reader/MongoDBODM/DeltaProductReader.php on line 40

**Comment by willy-ahva** [comment]
Hi !

I succeed to reproduce your problem. I'll inform you when it'll be fixed.

Thank you for report it !

Regards,
Willy

**Comment by willy-ahva** [comment]
Hi,

You can find your fix in this new tag :)

Regards,
Willy

**Comment by vbnet3d** [comment]
Thank you. Will this install with composer now, or do I have to wait until it merges into the master branch?
