### ISSUE TITLE
Update to version 1.2.1 on pim 1.3.5

### ISSUE THREAD

**Issue by jcpla** [akeneo/MagentoConnectorBundle#467]
Hello everybody,
I make an update of the connector today but I have an exception probably due to the merge friday : 

PHP Fatal error:  Class 'Pim\Bundle\MagentoConnectorBundle\DependencyInjection\Version' not found in /workspace/akeneo/www/vendor/akeneo/magento-connector-bundle/Pim/Bundle/MagentoConnectorBundle/DependencyInjection/PimMagentoConnectorExtension.php on line 59

The namespace for Version is not imported ?

Regards 
JC

**Comment by fitn** [comment]
Hi @jcpla 

Sorry about that. It seems that we introduced a regression in the last release. I'll work on right now.
You can work on the 1.2.0 to avoid this problem ;)

Regards,

**Comment by jcpla** [comment]
Hello Romain,
no pb, i can wait
Have a nice week

**Comment by fitn** [comment]
Hi @jcpla 

It's fixed ;) You can reinstall your vendor with the new tag 1.2.2.

Regards,
