### ISSUE TITLE
New error after installation

### ISSUE THREAD

**Issue by vbnet3d** [akeneo/MagentoConnectorBundle#469]
This error is being logged after a brand new installation: (PIM 1.3.5, w/MongoBD, Magento Connector 1.2.2)

PHP Catchable fatal error:  Argument 2 passed to Pim\\Bundle\\MagentoConnectorBundle\\Manager\\GroupManager::__construct() must be an instance of Pim\\Bundle\\MagentoConnectorBundle\\Entity\\Repository\\GroupRepository, instance of Pim\\Bundle\\CatalogBundle\\Entity\\Repository\\GroupRepository given, called in /var/www/pim-project/app/cache/prod/appProdProjectContainer.php on line 7555 and defined in /var/www/pim-project/vendor/akeneo/magento-connector-bundle/Pim/Bundle/MagentoConnectorBundle/Manager/GroupManager.php on line 31

It appears to be a naming issue - note "CatalogBundle"

**Comment by fitn** [comment]
Hi @vbnet3d 

I need more information to reproduce this issue. On which screen or job this error happens? Did you restart your Apache2 server?

Regards,

**Comment by vbnet3d** [comment]
It happens on any screen. I will have my sysadmin perform the restart and report back.

**Comment by vbnet3d** [comment]
That was the issue. Restarting Apache2 server resolved this. Thank you.

**Comment by fitn** [comment]
In production environment, you have to restart Apache2 cause you're using APC ;)

Regards,
