### ISSUE TITLE
Error when trying to export products into Magento

### ISSUE THREAD

**Issue by nhartse1** [akeneo/MagentoConnectorBundle#474]
The error that I'm getting is:

Error on Magento soap call to "http://beta.domain.com/index.php/api/soap/?wsdl" : "Error Fetching http headers". Called resource : "catalog_product.list" with parameters : []

Magento Verison: 1.8.1
PIM: 1.3

My team has been racking our brains trying to figure out the issue. Any help would be appreciated.

**Comment by fitn** [comment]
Hi @nhartse1 

This error comes from Magento not from the PIM. You can take a look at your Magento logs or Apache2 logs on Magento server. It comes from the fact that there is no response from Magento so maybe a Segmentation fault or something like that.

Regards,
