### ISSUE TITLE
Error: "catalog_product_attribute.options" with parameters : ["status",0]

### ISSUE THREAD

**Issue by linslin** [akeneo/MagentoConnectorBundle#482]
While tying a Product Export a error with "catalog_product_attribute.options" comes up:

`
An error occured during the export execution.
Error #0 in class Pim\Bundle\MagentoConnectorBundle\Webservice\SoapCallException: Error on Magento soap call to "http://deiters-magento.gjuce/api/soap/?wsdl" : "Requested attribute not found.". Called resource : "catalog_product_attribute.options" with parameters : ["status",0]
`

Do you have any clue why this is happening?

**Comment by damien-carcel** [comment]
This means that the connector does not find the attribute corresponding to the option. Either you didn't export your attributes properly before exporting products, or you don't have the same mapping between your attribute export job and your product export job.

Regards,
Damien

**Comment by linslin** [comment]
Thanks so far! :+1:  Yes, that makes sense. I tried to export the attributes first by using "MagentoAttributeExport". So families are exported nice, also clean families does work. But, at step `pim_magento_connector.steps.attribute_export.export.title` the nearly same error comes up here:

`
PIM_MAGENTO_CONNECTOR.STEPS.ATTRIBUTE_EXPORT.EXPORT.TITLE  Error on Magento soap call to "http://deiters-magento.gjuce/api/soap/?wsdl" : "Requested attribute not found.". Called resource : "catalog_product_attribute.options" with parameters : ["status",0]
`

**Comment by linslin** [comment]
Some more information - the following attribtues are selected atm and all of them does exists in Magento 1.9.2

`
name		
description	
short_description	
weight		
price		
tax_class_id	
`

**Comment by damien-carcel** [comment]
OK, so it seems that configuration is OK. But if you have any error during the attribute export, the product export will not work (don't forget you also need to export category before products).

You error make me think that you have on Akeneo side a « status » attribute that is not compatible with the one already present in Magento. What data do you use in Akeneo ? Are they the one provided by the Magento connector fixtures ? And did you have any data in you Magento or is it a new, clean installation ?

By the way, I take this opportunity to remember you that the Magento connector is deprecated and will be completely stopped (which means no more bug fix or support from Akeneo) in september, when Akeneo 1.4 is released. We strongly encourage all our users to migrate to PimGento as soon as possible. You can read more here to understand why: http://www.akeneo.com/goodbye-magentoconnectorbundle-hello-pimgento/

Regards,
Damien

**Comment by linslin** [comment]
Thanks for you answer. We don't invest more time in debugging, so we will switch to PIMGento. Thanks anyways!

Lin
